version: '3'
services:
  cockroachdb:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: cockroachdb
    volumes:
      - ../..:/data:Z
    tty: true
    expose:
      - "8080"
    network_mode: host

volumes:
  data-volume:
